sla_website/sla_website/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('socialmedia/', include('socialmedia.urls', namespace='socialmedia')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)

sla_website/socialmedia/urls.py
from django.urls import path
from . import views


app_name = 'socialmedia'

    
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
	#homepage

    path('<pk>/', views.DetailView.as_view(), name = 'detail'),

    path('post/add/', views.PostCreate.as_view(), name = 'add-post'),

    path('user/register/', views.UserFormView.as_view(), name = 'register'),

    #path('post//', views.PostCreate.as_view(), name = 'add-post'),

    #path('post/add/', views.PostCreate.as_view(), name = 'add-post'),

    #1. add users
    path('api/v1/users/', views.UserCreate.as_view(), name = 'add-user'),
    path('api/v1/users/<username>/', views.UserDelete.as_view(), name = 'remove-user'),


    path('api/v1/categories/', views.ListAddActsCategories.as_view(), name = 'list-add-acts'),
    path('api/v1/categories/<actType>/', views.DeleteActsCategories.as_view(), name = 'delete-acts'),

    path('api/v1/categories/<actType>/acts/', views.ListPostAct.as_view(), name = 'list-posts-for-act'),
    path('api/v1/categories/<actType>/acts/size/', views.ListPostsSize.as_view(), name = 'list-posts-size'),
    path('api/v1/categories/<actType>/acts?start=<startRange>&end=<endRange>/', views.ListPostRange.as_view(), name = 'list-posts-in-range'),

    path('api/v1/acts/upvote/', views.UpvotePost.as_view(), name = 'upvote-post'),

	path('api/v1/acts/<actID>/', views.RemovePost.as_view(), name = 'delete-post'),

    path('api/v1/acts/', views.AddPost.as_view(), name = 'upload-post'),    

	#6. List acts for a given category (when total #acts is less than 500)
	

	

	
]	

sla_website/socialmedia/models.py
from django.db import models
from django.urls import reverse
import datetime
from django.utils import timezone

class Acts(models.Model):
	actType = models.CharField(max_length=100, unique=True)

	#string representation of the db
	def __str__(self):
		return self.actType

class CustomUser(models.Model):
	username = models.CharField(max_length=100)
	password = models.CharField(max_length=40)

	def __str__(self):
		return self.username 


class Post(models.Model):
	act = models.ForeignKey(Acts, on_delete = models.CASCADE)
	user = models.ForeignKey(CustomUser, on_delete = models.CASCADE, null=True)

	#for actID, we use default ID Django gives for each model
	#name = models.CharField(max_length=100)
	caption = models.CharField(max_length=1000)
	#image = models.FileField()

	image = models.CharField(max_length = 2**32)
	upvotes = models.IntegerField(default = 0)
	timestamp = models.DateTimeField(default = timezone.now(), null = True)


	def get_absolute_url(self):
		return reverse('socialmedia:index')#, kwargs={'pk': self.pk})

	def __str__(self):
		return str(self.id) + ' - ' + self.act.actType

sla_website/socialmedia/forms.py
'''from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields'''

from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

sla_website/socialmedia/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm

from .models import Acts, Post, CustomUser

#from .models import CustomUser


from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

import json
import base64
import binascii
from django.core.files import File
import cv2
import os
from django.core.files.base import ContentFile



class IndexView(generic.ListView):
	model = Acts
	template_name = 'socialmedia/index.html'
	context_object_name = 'allActs'


#index view for the news feed of each ActType
class DetailView(generic.DetailView):
	model = Acts
	template_name = 'socialmedia/detail.html'
	context_object_name = 'act'
	
class PostCreate(CreateView):
	model = Post
	#template_name = 'socialmedia/detail.html'
	#context_object_name = 'posts'

	#fields for the user to fill out in the form
	fields = ['user', 'act', 'caption', 'image', 'timestamp']

'''class PostUpdate(UpdateView):
	model = Post
	#template_name = 'socialmedia/detail.html'
	#context_object_name = 'posts'

	#fields for the user to fill out in the form
	fields = ['act', 'name', 'caption', 'image']


class PostDelete(DeleteView):
	model = Post
	success_url = reverse_lazy('socialmedia:index')
'''


class UserFormView(View):
	form_class = UserForm
	template_name = 'socialmedia/registration_form.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			user.set_password(password)
			user.save()

			user = authenticate(username = username, password = password)

			if user is not None:
				if user.is_active:
					login(request, user)
					#return redirect('socialmedia:index')
					return render(request, 'socialmedia/index.html', {})
					#return Response(status=status.HTTP_201_CREATED)



			#return render(request, self.template_name, {'form': form})
			#return Response (status=status.HTTP_400_BAD_REQUEST)
			return render(request, 'socialmedia/index.html', {})



#	REST API 
#
#
#

#1 - Add user -  /api/v1/users

def check_sha1(password):
	n = len(password)
	if n != 40:
		return 0

	valid_chars = []
	for i in range(0, 10):
		valid_chars.append(str(i))
	
	string = 'abcdefABCDEF'
	for char in string:
		valid_chars.append(char)
	

	for char in password:
		if char not in valid_chars:
			return 0

	#valid password
	return 1

class UserCreate(APIView):
	def post(self, request, username=''):
		
		data = request.data
		username = data.get('username')
		password = data.get('password')

		if(not check_sha1(password)):
			return Response(status=status.HTTP_400_BAD_REQUEST)
		
		try:
			user = CustomUser.objects.get(username = username)
			return Response(status=status.HTTP_400_BAD_REQUEST)

		except:
			new_user = CustomUser()
			new_user.username = username
			new_user.password = password
			new_user.save()

			return Response(status=status.HTTP_201_CREATED)

#2. Remove user - /api/v1/users/{username}
class UserDelete(APIView):
	def delete(self, request, username):
		username = self.kwargs.get('username', None)
		
		try:
			user = CustomUser.objects.get(username = username)
			user.delete()
			return Response(status=status.HTTP_200_OK)

		except CustomUser.DoesNotExist:
			return Response(status=status.HTTP_400_BAD_REQUEST)


#3. List categories - api/v1/categories
#4. Add categories - api/v1/categories
class ListAddActsCategories(APIView):

	def get(self, request, actType=''):

		acts = Acts.objects.all()

		if(acts.count() == 0):
			return Response(status=status.HTTP_204_NO_CONTENT)

		count = dict()

		for act in acts:
			count[act.actType] = act.post_set.all().count()

		return Response(count, status=status.HTTP_200_OK)


	def post(self, request, actType=''):
		
		data = request.data
		data = data[0]


		try:
			Acts.objects.get(actType = str(data))
			
		except Acts.DoesNotExist:
			new_act = Acts()
			new_act.actType = str(data)
			new_act.save()

			return Response(status=status.HTTP_201_CREATED)

		return Response(status=status.HTTP_400_BAD_REQUEST)
		

#5. Remove category - /api/v1/categories/{categoryName}
class DeleteActsCategories(APIView):
	def delete(self, request, actType):
		data = self.kwargs.get('actType', None)

		try:
			act = Acts.objects.get(actType = str(data))

		except Acts.DoesNotExist:
			return Response(status=status.HTTP_400_BAD_REQUEST)

		act.delete()
		return Response(status=status.HTTP_200_OK)
					

		


#6. List acts for a given category - /api/v1/categories/{categoryName}/acts

class ListPostAct(APIView):
	def get(self, request, actType):
		data = self.kwargs.get('actType', None)
		
		act = Acts.objects.get(actType = data)
		count = act.post_set.all().count()

		
		if(count >= 500):
			return Response(status=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE)
		elif(count == 0):
			return Response(status=status.HTTP_204_NO_CONTENT)	
		
		response_dict= dict()
		response_data = []

		for post in act.post_set.all():
			print("usernmae", post.user)
			response_dict = {
				'username': str(post.user),
				'timestamp': post.timestamp,
				'actID': post.id,
				'caption': post.caption,
				#'imgB64': base64.b64encode((post.image).file.read())
				'imgB64': post.image
			}
			'''response_dict['actID'] = post.id
			response_dict['caption'] = post.caption
			response_dict['imgB64'] = base64.b64encode((post.image).file.read())'''
			response_data.append(response_dict)

		return Response(response_data, status=status.HTTP_200_OK)


#7. List number of acts for a given category - /api/v1/categories/{categoryName}/acts/size
class ListPostsSize(APIView):
	def get(self, request, actType):
		data = self.kwargs.get('actType', None)
		
		acts = Acts.objects.all()

		try:
			act = Acts.objects.get(actType = str(data))

		except Acts.DoesNotExist:
			return Response(status=status.HTTP_204_NO_CONTENT)

		count = act.post_set.all().count()
		return Response(count, status=status.HTTP_200_OK)


		


#8. Return number of acts for a given category in a given range (inclusive) - /api/v1/categories/{categoryName}/acts?start={startRange}&end={endRange}

class ListPostRange(APIView):
	def get(self, request, actType, startRange, endRange):
		Type = self.kwargs.get('actType', None)
		startRange = self.kwargs.get('startRange', None)
		EndRange = self.kwargs.get('endRange', None)

		try:
			acts = Acts.objects.get(actType = Type)
		except Acts.DoesNotExist:
			return Response(status= status.HTTP_204_NO_CONTENT)


		no_of_posts = Acts.objects.all().count()
		if(startRange < 1 or endRange > no_of_posts):
			return Response(status= status.HTTP_400_BAD_REQUEST)

		count = endRange-startRange+1
		if(count > 100 or count < 1):
			return Response(status = status.HTTP_413_REQUEST_ENTITY_TOO_LARGE)
		
		count2 = 0
		response_data = []
		for post in acts.post_set.all.reversed():
			if(count2 == count or count2 == no_of_posts):
				break;

			response_dict = dict()
			response_dict = {
				'username': str(post.user),
				'timestamp': post.timestamp,
				'actID': post.id,
				'caption': post.caption,
				#'imgB64': base64.b64encode((post.image).file.read())
				'imgB64': post.image
			}
			response_data.append(response_dict)
			count2 += 1

		return Response(response_data, status = status.HTTP_200_OK)


#9. Upvote an act - Route: /api/v1/acts/upvote

class UpvotePost(APIView):
	def post(self, request):
		postID = request.data[0]
		print('\n\n\n\n lol')
		try:
			post = Post.objects.get(id = postID)

		
		except Post.DoesNotExist:
			return Response(status=status.HTTP_400_BAD_REQUEST)
		
		post.upvotes += 1
		post.save()
		return Response(status = status.HTTP_200_OK)



#10. Remove an act - /api/v1/acts/{actId}

class RemovePost(APIView):
	#/api/v1/acts/{actId}
	def delete(self, request, actID):
		#actID is post.id here!!!

		data = self.kwargs.get('actID', None)
		#data = request.data
		try:
			post_del = Post.objects.get(pk = data)
			post_del.delete()
			return Response(status=status.HTTP_200_OK)

		except Post.DoesNotExist:
			return Response(status=status.HTTP_400_BAD_REQUEST)


#11. Upload an act - /api/v1/acts
class AddPost(APIView):	
	def post(self, request):
		
		data = request.data
		

		actID = data.get('actID')

		username = str(data.get('username'))
		actType = str(data.get('actType'))
		timestamp = data.get('timestamp')
		caption = data.get('caption')
		imgB64 = data.get('imgB64')
		
		

		posts = Post.objects.all()

		if actID in posts.values_list('id', flat=True):
			return Response(status=status.HTTP_400_BAD_REQUEST)

		try:
			image_binary = base64.b64decode(imgB64)
		except binascii.Error:
			return Response(status=status.HTTP_400_BAD_REQUEST)


		new_post = Post()

		new_post.act = Acts.objects.get(actType = str(actType))
		new_post.user = CustomUser.objects.get(username = str(username))

		new_post.id = actID
		new_post.caption = caption
		new_post.image = imgB64
		
		#timestamp read is in the format of “DD-MM-YYYY:SS-MM-HH”,
		dd = timestamp[0:2]
		mm = timestamp[3:5]
		yy = timestamp[6:10]
		ss = timestamp[11:13]
		minm = timestamp[14:16]
		hh = timestamp[17:19]

		#2019-02-09 11:17:13
		new_timestamp = yy+"-"+mm+"-"+dd+" "+hh+":"+minm+":"+ss
		print("\n\n\n\n\n", new_timestamp)

		try:
			new_post.timestamp = new_timestamp
			new_post.save()

		except:
			return Response(status=status.HTTP_400_BAD_REQUEST)	

		return Response(status=status.HTTP_201_CREATED)

	
				

				

sla_website/socialmedia/templates/socialmedia/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block title %}SelfieLessActs{% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'socialmedia/style.css' %}" />

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'socialmedia:index' %}">SelfieLessActs</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">          
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'socialmedia:add-post' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Post
                    </a>
                </li>
            </ul>
        </div>
        

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

sla_website/socialmedia/templates/socialmedia/detail.html
{% extends 'socialmedia/base.html' %}

{% block title %}
	{{act}}
{% endblock %}


{% block body %}
	<h2>{{ act }}</h2>
	
	{% if act.post_set.all %}
		<ul>
			{% for post in act.post_set.all reversed %}
			<pre>
				ID: {{post.id}}

				ImageString: {{post.image}}

				Caption: {{post.caption}}

				Time: {{post.timestamp}}

				User: {{post.user}}

			</pre>
			
			{% endfor %}
		</ul>
	{% else %}
		<h3>No acts to show!</h3>
	{% endif %}
{% endblock %}

sla_website/socialmedia/templates/socialmedia/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

sla_website/socialmedia/templates/socialmedia/index.html
{% extends 'socialmedia/base.html' %}



{% block body %}
	<h1>Selfie Less Acts</h1>
	<h2>Choose one below</h2>
	{% if allActs %}
		<ul>
			{% for act in allActs %}
			<li>
				<a href="{% url 'socialmedia:detail' act.id %}">
				{{act}}
				</a>
			</li>
			
			{% endfor %}
		</ul>
	{% else %}
		<h3>No acts to show!</h3>
	{% endif %}
{% endblock %}

sla_website/socialmedia/templates/socialmedia/post_form.html
{% extends 'socialmedia/base.html' %}

{% block title %} Add a new post {% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Post</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'socialmedia/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}

sla_website/socialmedia/templates/socialmedia/registration_form.html
{% extends 'socialmedia/base.html' %}

{% block title %} Add user {% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'socialmedia/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
</div>
{% endblock %}